server:
  host: "0.0.0.0"
  port: 3000

inference:
  provider: mock
  default_model: "mock-default"
  responses_dir: "./mocks"
  # base_url is not needed for mock provider

logging:
  level: debug
  format: pretty
  output: stdout